// SPDX-License-Identifier: FSL-1.1-Apache-2.0
use super::*;

/// The live shape: a workspace whose members (`acme-core`, `acme-cli`) carry
/// no `source`, next to registry crates. `acme-plugin` also resolves from the
/// registry at another version (a consumer pin), so it is NOT local-only.
const WORKSPACE_LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "acme-cli"
version = "0.8.8"
dependencies = [
 "acme-core",
 "clap",
 "tempfile",
]

[[package]]
name = "acme-core"
version = "0.8.8"
dependencies = [
 "serde",
]

[[package]]
name = "acme-plugin"
version = "0.8.8"

[[package]]
name = "acme-plugin"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "00"

[[package]]
name = "clap"
version = "4.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "clap_lex",
]

[[package]]
name = "clap_lex"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tempfile"
version = "3.10.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "fastrand",
]

[[package]]
name = "fastrand"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;

#[test]
fn packages_without_a_source_are_the_projects_own() {
    let local = local_packages(WORKSPACE_LOCK);
    assert!(local.contains(&("acme-core".to_string(), "0.8.8".to_string())));
    assert!(local.contains(&("acme-cli".to_string(), "0.8.8".to_string())));
    assert!(local.contains(&("acme-plugin".to_string(), "0.8.8".to_string())));
    assert!(!local.iter().any(|(n, _)| n == "serde" || n == "clap"));
}

#[test]
fn a_name_that_also_resolves_from_a_registry_is_not_local_only() {
    let names = local_only_names(WORKSPACE_LOCK);
    assert!(names.contains("acme-core"));
    assert!(names.contains("acme-cli"));
    assert!(
        !names.contains("acme-plugin"),
        "a registry copy exists, so a manifest naming it may mean the published crate"
    );
}

#[test]
fn crate_names_compare_with_hyphen_and_underscore_as_one() {
    assert_eq!(norm_crate_name("ed25519_dalek"), "ed25519-dalek");
    assert_eq!(norm_crate_name("Tower_HTTP"), "tower-http");
    assert_eq!(
        norm_crate_name("proc-macro2"),
        norm_crate_name("proc_macro2")
    );
}

#[test]
fn workspace_inherited_path_dependency_is_dropped_from_a_member_manifest() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let root = tmp.path();
    std::fs::create_dir(root.join(".git")).expect("git");
    std::fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/*\"]\n\n[workspace.dependencies]\n\
         acme-core = { path = \"crates/acme-core\", version = \"0.8.8\" }\n\
         serde = \"1\"\n",
    )
    .expect("root manifest");
    let member = root.join("crates").join("acme-cli");
    std::fs::create_dir_all(&member).expect("member dir");
    let manifest = member.join("Cargo.toml");
    std::fs::write(
        &manifest,
        "[package]\nname = \"acme-cli\"\n\n[dependencies]\nacme-core = { workspace = true }\n\
         serde.workspace = true\n",
    )
    .expect("member manifest");

    // No lockfile yet: the workspace's `path` declaration is the evidence.
    let local = workspace_local_crate_names(&manifest);
    assert!(local.contains("acme-core"), "{local:?}");
    assert!(!local.contains("serde"));

    let scanner = ProjectScanner::new();
    let mut signal = crate::ace::scanner::ProjectSignal {
        manifest_type: crate::ace::scanner::ManifestType::CargoToml,
        manifest_path: manifest.clone(),
        project_name: None,
        languages: vec!["rust".to_string()],
        frameworks: Vec::new(),
        dependencies: Vec::new(),
        dev_dependencies: Vec::new(),
        indirect_dependencies: Vec::new(),
        target_dependencies: Vec::new(),
        detected_at: String::new(),
        project_license: None,
        project_relevance: 1.0,
    };
    let text = std::fs::read_to_string(&manifest).expect("read");
    scanner.parse_cargo_toml(&text, &mut signal);
    assert!(signal.dependencies.contains(&"acme-core".to_string()));
    drop_local_crates(&local, &mut signal);
    assert_eq!(signal.dependencies, vec!["serde".to_string()]);

    // With a lockfile, its source-less members are local too.
    std::fs::write(root.join("Cargo.lock"), WORKSPACE_LOCK).expect("lock");
    let local = workspace_local_crate_names(&manifest);
    assert!(local.contains("acme-cli") && local.contains("acme-core"));
}

#[test]
fn the_lockfile_search_stops_at_the_repository_root() {
    let tmp = tempfile::tempdir().expect("tempdir");
    std::fs::write(tmp.path().join("Cargo.lock"), WORKSPACE_LOCK).expect("outer lock");
    let repo = tmp.path().join("repo");
    std::fs::create_dir_all(repo.join(".git")).expect("repo");
    let member = repo.join("crate");
    std::fs::create_dir_all(&member).expect("member");
    assert_eq!(
        nearest_cargo_lock(&member),
        None,
        "a lockfile outside the repository belongs to another project"
    );
}

#[test]
fn a_dev_dependency_and_what_only_it_pulls_in_are_dev() {
    let scope = CargoDevScope::new(
        WORKSPACE_LOCK,
        &["clap".to_string(), "serde".to_string()],
        &["tempfile".to_string()],
    );
    assert!(scope.is_dev_only("tempfile"));
    assert!(
        scope.is_dev_only("fastrand"),
        "reached only through tempfile"
    );
    assert_eq!(scope.label("fastrand"), "dev");
    assert!(!scope.is_dev_only("clap"));
    assert!(!scope.is_dev_only("clap_lex"));
    assert_eq!(
        scope.label("clap-lex"),
        "runtime",
        "underscore and hyphen agree"
    );
    assert_eq!(scope.label("acme-plugin"), "unknown");
    assert!(!scope.is_dev_only("acme-plugin"), "unknown is never dev");
}

#[test]
fn a_crate_both_dev_and_runtime_reachable_is_runtime() {
    // tempfile declared dev, but clap (runtime) also depends on it here.
    let lock = WORKSPACE_LOCK.replace(" \"clap_lex\",\n", " \"clap_lex\",\n \"tempfile\",\n");
    let scope = CargoDevScope::new(&lock, &["clap".to_string()], &["tempfile".to_string()]);
    assert!(!scope.is_dev_only("tempfile"));
    assert!(!scope.is_dev_only("fastrand"));
}

#[test]
fn edges_out_of_a_workspace_member_are_not_followed() {
    // acme-cli's lock entry lists tempfile (its dev-dependency); a runtime root
    // on the member must not make tempfile runtime.
    let scope = CargoDevScope::new(
        WORKSPACE_LOCK,
        &["acme-cli".to_string()],
        &["tempfile".to_string()],
    );
    assert!(scope.is_dev_only("tempfile"));
}

#[test]
fn garbage_lockfiles_yield_nothing() {
    assert!(parse_lock_packages("").is_empty());
    assert!(parse_lock_packages("[[package]]\nname = \"x\"\n").is_empty());
    assert!(local_only_names("not a lockfile").is_empty());
}
