// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdapterStatus = { 
/**
 * Source adapter name (e.g., "npm_registry", "crates_io", "osv", "github")
 */
adapter: string, 
/**
 * Current status: "checked", "not_checked", "failing", "disabled", "rate_limited", "stale"
 */
status: string, 
/**
 * When this adapter last successfully fetched data (ISO 8601 string or null)
 */
last_checked: string | null, };
