// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-adapter health status derived from the `feed_health` table.
 */
export type AdapterStatus = { source_type: string, feed_origin: string, 
/**
 * One of: "healthy", "failing", "circuit_open", "stale"
 */
status: string, consecutive_failures: bigint, last_success_at: string | null, last_failure_at: string | null, last_error: string | null, };
