// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-tier teaser for the Blind Spots lens: real aggregate counts only,
 * zero item detail. Computed from the same cached report path Signal pays
 * for (5-minute TTL), so the numbers can never diverge from what the full
 * lens would show.
 */
export type BlindSpotTeaser = { uncovered_count: number, stale_topic_count: number, missed_signal_count: number, 
/**
 * True when the report is cold-start-suppressed (<7 days of engagement
 * data). All counts are zero and the frontend renders nothing extra
 * (doctrine rule 6: no "no data yet" states).
 */
cold_start: boolean, };
