// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepAssessment } from "./DepAssessment";

export type BlindSpotAssessment = { assessments: Array<DepAssessment>, model: string, assessed_at: bigint, from_cache: boolean, 
/**
 * True when this is a persisted verdict whose stable key no longer
 * matches the current evidence — the view may re-assess. Always false
 * on a fresh or key-matching result.
 */
stale: boolean, };
