// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefNarrationReason } from "./BriefNarrationReason";

/**
 * Whether the configured model can NARRATE the morning brief, and why. Mirrors the exact
 * gate in `digest_commands` (`compute_has_llm` AND `is_brief_capable`) so the Settings hint
 * always tells the truth about what the next brief will actually do.
 */
export type BriefCapability = { 
/**
 * True → the brief is AI-narrated. False → the deterministic grounded floor is served
 * (always available, works offline, cannot hallucinate).
 */
brief_capable: boolean, 
/**
 * Classification for the UI to pick honest copy.
 */
reason: BriefNarrationReason, 
/**
 * The configured provider (e.g. "anthropic", "ollama", "none").
 */
provider: string, 
/**
 * The configured model id (empty when no provider is set).
 */
model: string, };
