// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the morning brief will (or won't) be AI-narrated. Drives the Settings/onboarding
 * hint copy so the user understands what they're getting — and how to upgrade it.
 */
export type BriefNarrationReason = "no_llm" | "model_too_weak" | "capable";
