// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFileMeta } from "./ContextFileMeta";

/**
 * One page of [`ContextFileMeta`], sorted by path. `total` counts every
 * context file, not just this page.
 */
export type ContextFilesPage = { files: Array<ContextFileMeta>, total: number, offset: number, limit: number, };
