// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Context Files panel lists: metadata only. Shipping every file's
 * contents moved ~26.6 MB in one IPC call for 1913 files (fresh-profile E2E
 * 2026-10-10) to render a filename and a line count.
 */
export type ContextFileMeta = { path: string, lines: number, size_bytes: number, 
/**
 * File extension, lowercase (`rs`, `md`, ...).
 */
kind: string, 
/**
 * Last-modified time, RFC 3339; `None` when the filesystem won't say.
 */
modified_at: string | null, };
