// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceCitation = { 
/**
 * Source (e.g. "hackernews", "github-advisory", "git-history",
 * "curated-corpus").
 */
source: string, 
/**
 * Human-readable title.
 */
title: string, 
/**
 * URL if available. `None` for inferred signals (git-history).
 */
url?: string | null, 
/**
 * Age in days. 0.0 = today.
 */
freshness_days: number, 
/**
 * Why this was selected as evidence. ≤ 200 chars. May be blanked in
 * LIST transport (the Preemption list never renders it — AD-035); the
 * detail path always carries the full note.
 */
relevance_note?: string, };
