// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactorKind } from "./FactorKind";

/**
 * One link in an item's explanation evidence chain.
 *
 * INVARIANTS (enforced by `scoring::explanation_chain` tests):
 * - `evidence` is never empty — a factor that cannot name concrete evidence
 *   (the package, the advisory id, the project, the interest term, the
 *   decision-window title) is not emitted at all.
 * - The chain is ordered by `weight_share` descending, and `weight_share`
 *   is monotone with the factor's actual score contribution.
 * - `display` never contains bare counts ("N signals confirmed", "N reasons").
 */
export type ExplanationFactor = { kind: FactorKind, 
/**
 * Short human-readable line, e.g. "Names your dependency axios".
 */
display: string, 
/**
 * The concrete evidence backing the display line, e.g.
 * "axios (direct, installed v1.6.2) — named in the item text".
 */
evidence: string, 
/**
 * This factor's share of the total explained contribution (0.0-1.0,
 * shares sum to <= 1.0 across the chain).
 */
weight_share: number, };
