// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The evidence category an [`ExplanationFactor`] belongs to.
 *
 * Ordered roughly by trust: a dependency/advisory edge is machine-verifiable
 * against the user's lockfiles; topic similarity is the weakest tier and must
 * self-disclose when it is the ONLY evidence (see the honesty-tail rule in
 * `scoring::explanation_chain`).
 */
export type FactorKind = "DependencyMatch" | "SecurityAdvisory" | "ContextMatch" | "InterestMatch" | "TopicMatch" | "DecisionWindow" | "SkillGap" | "CommunitySignal";
