// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LensHints = { briefing?: boolean, preemption?: boolean, blind_spots?: boolean, evidence?: boolean, 
/**
 * Rendering hint (Phase 2c, platform-aware deps): the item is relevant only
 * to a build target the user does NOT build on the host (e.g. a
 * `cfg(not(windows))` crate's advisory on a Windows machine). The lens
 * groups such items into a collapsed "other build targets" section and tags
 * them with a badge — surfaced, de-prioritised, never hidden (a
 * cross-platform dev still reaches them). `false` for all normal items.
 * Set by the preemption + blind-spots materializers when the dep is
 * platform-inactive in every tracked project/target. Defaults `false` for
 * back-compat with pre-Phase-2c items.
 */
other_build_target?: boolean, 
/**
 * Rendering hint (Phase 1 dependency-upgrade plan): the item is a ranked
 * upgrade-plan step ("upgrade X — clears N advisories across M projects"),
 * so the Preemption lens groups it under the "Upgrade Plan" section instead
 * of the flat advisory list. Set by `upgrade_plan::build_upgrade_plan`.
 * `false` for all normal items; defaults `false` for back-compat.
 */
upgrade_plan?: boolean, 
/**
 * Rendering hint (2026-08-31 live audit): the coverage-gap dependency has
 * ZERO available signals — sources were checked (or haven't run) and found
 * nothing, so there is no "unreviewed activity" to speak of. The Blind
 * Spots lens groups such gaps under an honest "no signal coverage" section
 * instead of inflating the "Drifting / unreviewed activity" tier with rows
 * that literally say "found no results". Set by
 * `uncovered_dep_to_evidence_item` when `available_signal_count == 0`.
 * `false` for all normal items; defaults `false` for back-compat.
 */
no_coverage?: boolean, 
/**
 * Rendering hint (2026-09-07 adversarial audit): the dependency is in the
 * lockfile but this host NEVER COMPILES it — cargo resolves it for no
 * target/feature combination the user builds. A strictly stronger claim
 * than [`Self::other_build_target`], which says the dep belongs to a
 * build target the user does have. Live cause: a HIGH "version-confirmed"
 * advisory for `quinn-proto`, an optional dependency of a `reqwest`
 * feature this tree does not enable. Always accompanies
 * `other_build_target` (both mean "de-prioritised, still surfaced"); this
 * one only selects the more precise copy. Set by the preemption +
 * blind-spots materializers from
 * `platform_filter::PlatformInactivePackages::is_lockfile_only`.
 * `false` for all normal items; defaults `false` for back-compat.
 */
lockfile_only?: boolean, 
/**
 * Rendering hint (2026-09-07 adversarial audit): the item is the single
 * summary standing in for every finding against ONE dormant project.
 * A repo the user still owns but has not touched in months was silently
 * absent from Preemption — the relevance floor kept its lockfile out of
 * the walk entirely, so 31 known-vulnerable packages in `navcal` showed
 * up nowhere at all. It is now named once, quietly, as a footer row
 * rather than as N alarming rows about a repo nobody is deploying. Set by
 * `evidence::dormant_notice::collapse_dormant_alerts`. `false` for all
 * normal items; defaults `false` for back-compat.
 */
dormant_notice?: boolean, };
