// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseChangeEntry } from "./ReleaseChangeEntry";
import type { ReleaseChangesStatus } from "./ReleaseChangesStatus";

/**
 * "What changed" between the installed and the announced version.
 */
export type ReleaseChanges = { ecosystem: string, package: string, from_version: string, to_version: string, status: ReleaseChangesStatus, 
/**
 * The changelog's path inside the archive ("CHANGELOG.md").
 */
file: string | null, 
/**
 * Release sections in (from, to], newest first as the changelog lists them.
 */
versions: Array<string>, 
/**
 * The changelog reaches both ends of the range; false = partial history.
 */
covers_range: boolean, breaking: number, features: number, fixes: number, security: number, deprecations: number, other: number, top_breaking: Array<ReleaseChangeEntry>, 
/**
 * Where the user can read the changelog itself (a link, never fetched).
 */
source_url: string | null, 
/**
 * Why there is nothing to show, in plain words.
 */
reason: string | null, };
