// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the release card says about one release.
 */
export type ReleaseChangesStatus = "found" | "no_sections_in_range" | "no_changelog" | "unparsed" | "refused" | "unavailable";
