// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry shown on the card.
 */
export type ReleaseChangeEntry = { 
/**
 * The release the entry belongs to.
 */
version: string, 
/**
 * Sanitised entry text (control / bidi characters stripped, ≤ 400 chars).
 */
text: string, 
/**
 * The heading or parent bullet it sits under ("Removed").
 */
under: string | null, };
