// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterStatus } from "./AdapterStatus";

/**
 * Aggregate summary of all source adapter health.
 */
export type SourceHealthSummary = { adapters: Array<AdapterStatus>, total_active: number, total_failing: number, total_disabled: number, };
