// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which entitlement tier a feed was materialized for. Lets the frontend
 * distinguish the free security floor (deterministic OSV-verified items
 * only) from the full Signal feed without inferring it from item counts.
 */
export type TierScope = "free_floor" | "full";
