// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterStatus } from "./AdapterStatus";

export type UncoveredDep = { name: string, 
/**
 * npm, cargo, pip, etc.
 */
dep_type: string, projects_using: Array<string>, days_since_last_signal: number, 
/**
 * Signals that exist but the user didn't see
 */
available_signal_count: number, 
/**
 * critical, high, medium, low
 */
risk_level: string, 
/**
 * How the dependency was matched: "exact_registry", "advisory", "title_heuristic", or "none"
 */
match_type: string, 
/**
 * Why this dep has no/limited coverage. Provides honest diagnostics instead of
 * the misleading "none of your sources cover it" language.
 * Examples: "not_checked", "checked_no_results", "adapter_failing", "adapter_disabled", "unknown_ecosystem", "weak_matches_only"
 */
coverage_reason: string | null, 
/**
 * Which source adapters were searched for this dependency and their status.
 * Each entry is like "npm_registry: checked 2h ago" or "osv: adapter_failing".
 */
adapters_searched: Array<AdapterStatus>, 
/**
 * Whether this dependency is built on the host platform. `false` only when
 * the dep is gated to a target the user does not build (e.g. a
 * `cfg(not(windows))` crate on Windows) AND inactive in EVERY tracked
 * project/target. Platform-inactive deps are de-prioritised (urgency capped
 * to Watch in `uncovered_dep_to_evidence_item`) but never hidden — a
 * cross-platform dev still reaches them. Defaults to `true` (active/visible)
 * for back-compat with pre-Phase-2b reports and pre-Phase-85 DBs.
 */
platform_active: boolean, };
