// SPDX-License-Identifier: FSL-1.1-Apache-2.0
import { useState, useEffect, useCallback } from 'react';

import type { SourceRelevance, AnalysisProgress } from '../types';
import { useAppStore } from '../store';
import { useShallow } from 'zustand/react/shallow';
import type { AppState } from '../store/types';
import { safeListen, type UnlistenFn } from '../lib/tauri-events';
import type { NarrationEvent } from './analysis-utils';
import {
  handleAnalysisProgress,
  handleAnalysisComplete,
  handleAnalysisError,
  handleSourceError,
  handleNetworkOffline,
  handleEmbeddingMode,
  handleStartAnalysisFromTray,
  handleNavigateToSignals,
  createBackgroundResultsHandler,
  handleBriefingAutoGenerated,
  handleMorningBriefingReady,
  handleMorningBriefingSynthesis,
  handleAnomalyDetected,
  handleDigestGenerated,
  handlePartialResults,
  handleStacksAutoDetected,
  handleCalibrationDrift,
  createNarrationHandler,
} from './analysis-event-handlers';
import type { MorningBriefingReadyPayload } from './analysis-event-handlers';
export type { NarrationEvent } from './analysis-utils';

/**
 * Analysis hook — thin wrapper around Zustand store.
 * Sets up Tauri event listeners that write directly to the store.
 * All state lives in the store; this hook adds no local state.
 */
export function useAnalysis(
  _addToast?: (type: 'success' | 'error' | 'warning' | 'info', message: string) => void,
  onBackgroundItems?: (itemIds: number[]) => void,
) {
  const state = useAppStore(
    useShallow(s => ({
      contextFiles: s.appState.contextFiles,
      relevanceResults: s.appState.relevanceResults,
      nearMisses: s.appState.nearMisses,
      loading: s.appState.loading,
      analysisComplete: s.appState.analysisComplete,
      lastAnalyzedAt: s.appState.lastAnalyzedAt,
    }))
  );
  const expandedItem = useAppStore(s => s.expandedItem);
  const isBrowserMode = useAppStore(s => s.isBrowserMode);
  const setExpandedItem = useAppStore(s => s.setExpandedItem);
  const startAnalysis = useAppStore(s => s.startAnalysis);
  const loadContextFiles = useAppStore(s => s.loadContextFiles);
  const clearContext = useAppStore(s => s.clearContext);
  const indexContext = useAppStore(s => s.indexContext);

  // Live analysis narration events
  const [narrationEvents, setNarrationEvents] = useState<NarrationEvent[]>([]);

  const clearNarrationEvents = useCallback(() => {
    setNarrationEvents([]);
  }, []);

  // Set up event listeners for background analysis — all write to store
  useEffect(() => {
    let unlistens: UnlistenFn[] = [];

    const setupListeners = async () => {
      const results = await Promise.all([
        safeListen<AnalysisProgress>('analysis-progress', handleAnalysisProgress),
        safeListen<SourceRelevance[]>('analysis-complete', handleAnalysisComplete),
        safeListen<string>('analysis-error', handleAnalysisError),
        safeListen<{ source: string; error: string; retry_count: number }>('source-error', handleSourceError),
        safeListen('network-offline', handleNetworkOffline),
        safeListen<{ mode: string; reason?: string }>('embedding-mode', handleEmbeddingMode),
        safeListen('start-analysis-from-tray', handleStartAnalysisFromTray),
        safeListen<{ item_id?: number }>('navigate-to-signals', handleNavigateToSignals),
        safeListen<SourceRelevance[]>('background-results', createBackgroundResultsHandler(onBackgroundItems)),
        safeListen<{ briefing: string; model?: string }>('briefing-auto-generated', handleBriefingAutoGenerated),
        safeListen<MorningBriefingReadyPayload>('morning-briefing-ready', handleMorningBriefingReady),
        safeListen<{ synthesis: string; clusters?: Array<{ insight: string; evidence_ids: number[]; action: string; confidence: number }> }>('morning-briefing-synthesis', handleMorningBriefingSynthesis),
        safeListen<{ type: string; severity: string; description: string }>('anomaly-detected', handleAnomalyDetected),
        safeListen<{ item_count: number }>('digest-generated', handleDigestGenerated),
        safeListen<SourceRelevance[]>('partial-results', handlePartialResults),
        safeListen<string[]>('stacks-auto-detected', handleStacksAutoDetected),
        safeListen<{ task: string; reason: string }>('calibration-drift', handleCalibrationDrift),
        safeListen<{ narration_type: string; message: string; source: string | null; relevance: number | null }>('analysis-narration', createNarrationHandler(setNarrationEvents)),
      ]);

      unlistens = results;
    };

    void setupListeners();

    return () => {
      for (const unlisten of unlistens) unlisten();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps -- stable callback ref
  }, []);

  // Hydration from backend cache is handled by useAppListeners (use-app-listeners.ts)
  // which also handles the auto-analysis fallback — no duplicate fetch needed here.
  // Context files are loaded lazily by ResultsView when the collapsible context
  // panel is opened. Loading them here recursively reads project files on every
  // app mount, which is unnecessary for the default Brief view.

  const setStatus = useCallback((status: string) => {
    useAppStore.getState().setAppState({ status });
  }, []);

  // setState wrapper for App.tsx compatibility (accepts updater function)
  const setState = useCallback((updater: ((s: AppState) => AppState) | Partial<AppState>) => {
    if (typeof updater === 'function') {
      useAppStore.getState().setAppStateFull(updater);
    } else {
      useAppStore.getState().setAppState(updater);
    }
  }, []);

  return {
    state,
    setState,
    expandedItem,
    setExpandedItem,
    isBrowserMode,
    loadContextFiles,
    clearContext,
    indexContext,
    startAnalysis,
    setStatus,
    narrationEvents,
    clearNarrationEvents,
  };
}
