// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphCluster } from "./GraphCluster";
import type { GraphEdge } from "./GraphEdge";
import type { GraphMeta } from "./GraphMeta";
import type { GraphNode } from "./GraphNode";

export type ContentGraph = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, clusters: Array<GraphCluster>, meta: GraphMeta, };
