// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DomainPrecision = { domain: string, 
/**
 * Precision score: None when insufficient data (< MIN_PRECISION_DATA_POINTS),
 * Some(0.0..=1.0) when enough evidence exists.
 */
precision: number | null, total_surfaced: number, 
/**
 * Engagement count (user clicked/acted on item). NOT a true positive signal.
 */
engaged: number, false_positives: number, 
/**
 * Validated count (explicitly confirmed relevant by user).
 */
validated: number, };
