// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mutual top-k nearest neighbours by embedding — the relation themes are
 * built from. (Signal-chain and convergence edges were display-only and
 * left with the node canvas.)
 */
export type EdgeType = "semantic";
