// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedbackLiveness = { 
/**
 * `trust_events` rows of type `surfaced` inside the window.
 */
surfaced_14d: bigint, 
/**
 * Explicit relevant / not-relevant ratings (`feedback` rows) in the window.
 */
feedback_14d: bigint, 
/**
 * Active `interactions` rows (click, save, engagement_complete, ...) in
 * the window; passive `scroll` / `ignore` telemetry is excluded.
 */
interactions_14d: bigint, 
/**
 * All-time latest rating, DB timestamp format (`YYYY-MM-DD HH:MM:SS`, UTC).
 */
last_feedback_at: string | null, 
/**
 * All-time latest active interaction, same format.
 */
last_interaction_at: string | null, };
