// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNode = { id: bigint, title: string, url: string | null, source_type: string, relevance_score: number, signal_type: string | null, signal_priority: string | null, created_at: string, primary_topic: string | null, 
/**
 * The theme this node belongs to; `None` for stack items (they get
 * their own column) and for items related to no theme.
 */
cluster_id: string | null, 
/**
 * Total items this node represents (1 = a plain item; >1 = a story that
 * collapsed near-duplicate items behind one representative).
 */
member_count: number, 
/**
 * Item ids of all members including the representative — the detail
 * panel hydrates member rows from these via `get_graph_node_details`.
 */
member_ids: Array<bigint>, 
/**
 * Content category: "security" | "release" | "discussion" | "research".
 * The primary color channel — source identity moved to the tooltip.
 */
category: string, 
/**
 * Any member carries the scoring pipeline's strong-grounding verdict
 * (the same predicate as Signal's "Affects You" pool) — the map's
 * "Your stack" column.
 */
affects_you: boolean, };
