// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphMeta = { total_items: number, total_edges: number, cluster_count: number, time_window_days: number, edge_threshold: string, };
