// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeType } from "./EdgeType";

export type GraphEdge = { source: bigint, target: bigint, edge_type: EdgeType, weight: number, label: string | null, methods: Array<string>, };
