// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphMeta = { total_items: number, total_edges: number, cluster_count: number, 
/**
 * Nodes that represent 2+ collapsed items.
 */
story_count: number, 
/**
 * Items folded behind story representatives (not separately visible).
 */
collapsed_items: number, 
/**
 * Items selected for the window but not on the map: non-curated isolated
 * singletons beyond the shelf cap, plus items behind stories truncated by
 * the node budget. Curated items are never hidden (corpus parity).
 */
hidden_items: number, 
/**
 * Total items matching the corpus selection in this window, independent
 * of the node budget — lets the UI state real coverage ("top N of M")
 * instead of implying the map is exhaustive.
 */
window_candidates: number, time_window_days: number, edge_threshold: string, 
/**
 * Pair-count-weighted mean of per-cluster coherence — the graph's own
 * quality gauge, comparable across corpora and windows. `None` when no
 * cluster has 2+ members.
 */
mean_cluster_coherence: number | null, 
/**
 * Nodes whose story carries a persisted feed-curation verdict
 * (corpus parity, Phase 95). The remainder are young not-yet-judged
 * items; this count makes the curation ramp measurable, not hidden.
 */
curated_items: number, };
