// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNode = { id: bigint, title: string, url: string | null, source_type: string, relevance_score: number, signal_type: string | null, signal_priority: string | null, created_at: string, primary_topic: string | null, cluster_id: string | null, 
/**
 * Total items this node represents (1 = a plain item; >1 = a story that
 * collapsed near-duplicate items behind one representative).
 */
member_count: number, 
/**
 * Titles of the collapsed siblings (representative excluded), capped.
 */
member_titles: Array<string>, 
/**
 * Item ids of all members including the representative.
 */
member_ids: Array<bigint>, 
/**
 * Content category: "security" | "release" | "discussion" | "research".
 * The primary color channel — source identity moved to the tooltip.
 */
category: string, 
/**
 * Any member is linked to one of the user's declared dependencies
 * (dep_linker) — rendered as the gold "touches your stack" ring.
 */
affects_you: boolean, x: number, y: number, };
