// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphCluster = { id: string, label: string, node_ids: Array<bigint>, source_count: number, centroid_x: number, centroid_y: number, };
