// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNode = { id: bigint, title: string, url: string | null, source_type: string, relevance_score: number, signal_type: string | null, signal_priority: string | null, created_at: string, primary_topic: string | null, cluster_id: string | null, x: number, y: number, };
