// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A theme: a Louvain community of 2+ non-stack items. Emitted in display
 * order — related themes adjacent (themes.rs).
 */
export type GraphCluster = { id: string, label: string, node_ids: Array<bigint>, source_count: number, 
/**
 * Mean pairwise embedding cosine among members — how tight this theme
 * really is. Emitted so coherence is measurable on every corpus, not
 * asserted (Wave 4 self-measurement).
 */
coherence: number, 
/**
 * Stack items (`affects_you`) that belonged to this theme's community.
 * They live in the map's "Your stack" column, not in the theme; this
 * keeps the link so the theme can say which of the user's packages it
 * is about (blinded audit 2026-10-05: raters could not tell which news
 * related to the stack once it moved to its own column).
 */
stack_node_ids: Array<bigint>, };
