// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//! Reader tests on real-format samples, cut down from the 2026-10-10
//! conformance corpus (jest, hono, httpbin, fastapi templates, traefik, caddy).

use std::path::Path;

use super::*;

fn read(name: &str, format: LockFormat, content: &str) -> LockfileRead {
    match read_text(Path::new(name), format, content) {
        LockfileOutcome::Read(read) => read,
        other => panic!("{name} did not read: {other:?}"),
    }
}

fn ids(read: &LockfileRead) -> Vec<String> {
    let mut v: Vec<String> = read
        .packages
        .iter()
        .map(|p| format!("{}@{}", p.name, p.version))
        .collect();
    v.sort();
    v
}

fn find<'a>(read: &'a LockfileRead, name: &str, version: &str) -> &'a LockedPackage {
    read.packages
        .iter()
        .find(|p| p.name == name && p.version == version)
        .unwrap_or_else(|| panic!("{name}@{version} in {:?}", ids(read)))
}

#[test]
fn package_lock_v3_keeps_nested_copies_aliases_and_drops_links() {
    let lock = r#"{"name":"app","lockfileVersion":3,"packages":{
        "":{"name":"app","workspaces":["packages/*"]},
        "node_modules/semver":{"version":"7.6.0"},
        "node_modules/@babel/core":{"version":"7.24.0","dev":true},
        "node_modules/@babel/core/node_modules/semver":{"version":"6.3.1","dev":true},
        "node_modules/string-width-cjs":{"name":"string-width","version":"4.2.3"},
        "node_modules/my-lib":{"resolved":"packages/my-lib","link":true},
        "packages/my-lib":{"name":"my-lib","version":"1.0.0"},
        "packages/my-lib/node_modules/lodash":{"version":"4.17.20"},
        "node_modules/gitdep":{"version":"git+ssh://git@github.com/x/y.git#abc"}
    }}"#;
    let read = read("package-lock.json", LockFormat::NpmLock, lock);
    assert_eq!(
        ids(&read),
        [
            "@babel/core@7.24.0",
            "lodash@4.17.20",
            "semver@6.3.1",
            "semver@7.6.0",
            "string-width@4.2.3"
        ]
    );
    assert!(find(&read, "semver", "7.6.0").primary);
    assert!(!find(&read, "semver", "6.3.1").primary);
    assert_eq!(find(&read, "semver", "6.3.1").scope, DepScope::Dev);
    assert_eq!(find(&read, "semver", "7.6.0").scope, DepScope::Runtime);
    assert_eq!(read.non_registry_entries, 3, "link + workspace dir + git");
}

#[test]
fn package_lock_v1_walks_nested_dependencies_and_aliases() {
    let lock = r#"{"lockfileVersion":1,"dependencies":{
        "express":{"version":"4.18.2","dependencies":{
            "debug":{"version":"2.6.9","dependencies":{"ms":{"version":"2.0.0"}}}}},
        "debug":{"version":"4.3.4","dev":true},
        "wrap-cjs":{"version":"npm:wrap-ansi@7.0.0"}
    }}"#;
    let read = read("package-lock.json", LockFormat::NpmLock, lock);
    assert_eq!(
        ids(&read),
        [
            "debug@2.6.9",
            "debug@4.3.4",
            "express@4.18.2",
            "ms@2.0.0",
            "wrap-ansi@7.0.0"
        ]
    );
    assert!(find(&read, "debug", "4.3.4").primary);
    assert!(!find(&read, "debug", "2.6.9").primary);
}

#[test]
fn an_unparseable_package_lock_is_a_failure_not_an_empty_read() {
    let outcome = read_text(
        Path::new("package-lock.json"),
        LockFormat::NpmLock,
        "{ not json",
    );
    assert!(
        matches!(outcome, LockfileOutcome::Failed { .. }),
        "{outcome:?}"
    );
}

#[test]
fn yarn_classic_reads_scoped_aliased_and_counts_git_entries() {
    let lock = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.12.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#dcfc826b"
  dependencies:
    "@babel/highlight" "^7.12.13"

lodash@^4.17.20:
  version "4.17.21"

"string-width-cjs@npm:string-width@^4.2.0":
  version "4.2.3"

"forked@git+https://github.com/me/forked.git#abc":
  version "1.0.0"
"#;
    let read = read("yarn.lock", LockFormat::YarnClassic, lock);
    assert_eq!(
        ids(&read),
        [
            "@babel/code-frame@7.12.13",
            "lodash@4.17.21",
            "string-width@4.2.3"
        ]
    );
    assert_eq!(read.non_registry_entries, 1);
}

#[test]
fn yarn_berry_reads_the_yaml_version_and_skips_the_workspace() {
    let lock = r#"# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 6
  cacheKey: 8

"@babel/code-frame@npm:^7.0.0, @babel/code-frame@npm:^7.10.4":
  version: 7.12.13
  resolution: "@babel/code-frame@npm:7.12.13"
  dependencies:
    "@babel/highlight": ^7.12.13
  checksum: 471532bb7c
  languageName: node
  linkType: hard

"jest-monorepo@workspace:.":
  version: 0.0.0-use.local
  resolution: "jest-monorepo@workspace:."
  languageName: unknown
  linkType: soft

"resolve@patch:resolve@^1.20.0#~builtin<compat/resolve>":
  version: 1.22.1
  resolution: "resolve@patch:resolve@npm%3A1.22.1#~builtin<compat/resolve>::version=1.22.1&hash=07638b"
  languageName: node
  linkType: hard

"resolve@npm:^1.20.0":
  version: 1.22.1
  resolution: "resolve@npm:1.22.1"
  languageName: node
  linkType: hard
"#;
    let read = read("yarn.lock", LockFormat::YarnClassic, lock);
    assert_eq!(read.format, LockFormat::YarnBerry);
    assert_eq!(ids(&read), ["@babel/code-frame@7.12.13", "resolve@1.22.1"]);
    assert_eq!(read.non_registry_entries, 1, "the workspace itself");
}

#[test]
fn bun_lock_reads_nested_copies_with_scope() {
    let lock = r#"{
  "lockfileVersion": 1,
  "workspaces": {
    "": {
      "name": "app",
      "dependencies": { "next": "^15.0.0", },
      "devDependencies": { "typescript": "^5", },
    },
    "packages/ui": { "name": "ui", },
  },
  "packages": {
    "next": ["next@15.0.3", "", { "dependencies": { "postcss": "8.4.31", }, }, "sha512-a"],
    "next/postcss": ["postcss@8.4.31", "", {}, "sha512-b"],
    "postcss": ["postcss@8.4.49", "", {}, "sha512-c"],
    "typescript": ["typescript@5.6.3", "", {}, "sha512-d"],
    "ui": ["ui@workspace:packages/ui"],
  }
}"#;
    let read = read("bun.lock", LockFormat::Bun, lock);
    assert_eq!(
        ids(&read),
        [
            "next@15.0.3",
            "postcss@8.4.31",
            "postcss@8.4.49",
            "typescript@5.6.3"
        ]
    );
    assert_eq!(find(&read, "postcss", "8.4.31").scope, DepScope::Runtime);
    assert!(!find(&read, "postcss", "8.4.31").primary);
    assert_eq!(find(&read, "postcss", "8.4.49").scope, DepScope::Unknown);
    assert!(find(&read, "postcss", "8.4.49").primary);
    assert_eq!(find(&read, "typescript", "5.6.3").scope, DepScope::Dev);
    assert_eq!(read.non_registry_entries, 1);
}

#[test]
fn poetry_pre_1_0_alphabetical_keys_and_category() {
    let lock = r#"[[package]]
category = "main"
description = "Python HTTP for Humans."
name = "requests"
optional = false
python-versions = ">=3.7"
version = "2.31.0"

[package.dependencies]
urllib3 = ">=1.21.1"

[[package]]
category = "dev"
name = "pytest"
version = "7.4.0"

[[package]]
name = "mylib"
version = "0.1.0"

[package.source]
type = "directory"
url = "../mylib"

[metadata]
content-hash = "abc"

[metadata.files]
requests = []
"#;
    let read = read("poetry.lock", LockFormat::Poetry, lock);
    assert_eq!(ids(&read), ["pytest@7.4.0", "requests@2.31.0"]);
    assert_eq!(find(&read, "pytest", "7.4.0").scope, DepScope::Dev);
    assert_eq!(find(&read, "requests", "2.31.0").scope, DepScope::Runtime);
    assert_eq!(read.non_registry_entries, 1);
}

#[test]
fn uv_lock_skips_the_project_and_reads_registry_packages() {
    let lock = r#"version = 1
requires-python = ">=3.10"

[[package]]
name = "anyio"
version = "4.4.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "idna" },
    { name = "sniffio" },
]
sdist = { url = "https://files.pythonhosted.org/anyio-4.4.0.tar.gz", hash = "sha256:a" }
wheels = [
    { url = "https://files.pythonhosted.org/anyio-4.4.0-py3-none-any.whl", hash = "sha256:b" },
]

[[package]]
name = "app"
version = "0.1.0"
source = { editable = "." }
dependencies = [
    { name = "anyio" },
]

[package.metadata]
requires-dist = [{ name = "anyio", specifier = ">=4" }]

[[package]]
name = "idna"
version = "3.7"
source = { registry = "https://pypi.org/simple" }
"#;
    let read = read("uv.lock", LockFormat::Uv, lock);
    assert_eq!(ids(&read), ["anyio@4.4.0", "idna@3.7"]);
    assert_eq!(read.non_registry_entries, 1);
}

#[test]
fn pipfile_lock_default_and_develop() {
    let lock = r#"{
    "_meta": {"hash": {"sha256": "x"}, "pipfile-spec": 6},
    "default": {
        "flask": {"hashes": ["sha256:a"], "index": "pypi", "version": "==1.0.2"},
        "mylib": {"editable": true, "path": "."}
    },
    "develop": {
        "pytest": {"version": "==3.6.3"}
    }
}"#;
    let read = read("Pipfile.lock", LockFormat::Pipfile, lock);
    assert_eq!(ids(&read), ["flask@1.0.2", "pytest@3.6.3"]);
    assert_eq!(find(&read, "pytest", "3.6.3").scope, DepScope::Dev);
    assert_eq!(read.non_registry_entries, 1);
}

#[test]
fn requirements_pins_hashes_extras_markers_and_includes() {
    let tmp = tempfile::tempdir().unwrap();
    let base = tmp.path().join("base.txt");
    std::fs::write(&base, "click==8.1.7\n-r requirements-dev.txt\n").unwrap();
    std::fs::write(
        tmp.path().join("requirements-dev.txt"),
        "-r base.txt\npytest==8.0.0\n",
    )
    .unwrap();
    let main = tmp.path().join("requirements.txt");
    let content = "\
# Reference stack
-r base.txt
aiohttp==3.9.1 \\
    --hash=sha256:aaa \\
    --hash=sha256:bbb
pillow==10.3.0  # imaging
fastapi[all]==0.111.0
uvicorn==0.29.0 ; python_version >= '3.8'
weird===1.0.0
numpy>=1.26.0
django==4.2.*
-e .
git+https://github.com/x/y.git#egg=y
";
    std::fs::write(&main, content).unwrap();
    let read = read(
        &main.display().to_string(),
        LockFormat::Requirements,
        content,
    );
    assert_eq!(
        ids(&read),
        [
            "aiohttp@3.9.1",
            "click@8.1.7",
            "fastapi@0.111.0",
            "pillow@10.3.0",
            "pytest@8.0.0",
            "uvicorn@0.29.0",
            "weird@1.0.0"
        ]
    );
}

#[test]
fn requirements_variants_and_requirements_dir_are_found() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path();
    for name in [
        "requirements.txt",
        "requirements-dev.txt",
        "_test_minimum_requirements.txt",
        "notes.txt",
    ] {
        std::fs::write(dir.join(name), "x==1.0\n").unwrap();
    }
    std::fs::create_dir_all(dir.join("requirements")).unwrap();
    std::fs::write(dir.join("requirements").join("base.txt"), "y==2.0\n").unwrap();
    let names: Vec<String> = requirements_files(dir)
        .iter()
        .map(|p| p.file_name().unwrap().to_string_lossy().to_string())
        .collect();
    assert_eq!(
        names,
        [
            "_test_minimum_requirements.txt",
            "base.txt",
            "requirements-dev.txt",
            "requirements.txt"
        ]
    );
    assert!(
        requirements_files(&dir.join("requirements")).is_empty(),
        "the parent owns requirements/"
    );
}

const GO_MOD_117: &str = "module example.com/app

go 1.21

require (
	github.com/gin-gonic/gin v1.9.1
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	github.com/old/thing v1.0.0
	github.com/local/thing v0.1.0
)

require github.com/pkg/errors v0.9.1+incompatible // indirect

replace github.com/old/thing => github.com/new/thing v1.2.0

replace github.com/local/thing => ../thing
";

#[test]
fn go_mod_117_is_the_build_list_with_replaces_applied() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("go.mod");
    // A go.sum full of historical versions must NOT be read for go >= 1.17.
    std::fs::write(
        tmp.path().join("go.sum"),
        "github.com/gin-gonic/gin v1.6.0 h1:x=\ngithub.com/hist/only v0.1.0/go.mod h1:y=\n",
    )
    .unwrap();
    let read = read(&path.display().to_string(), LockFormat::GoMod, GO_MOD_117);
    assert_eq!(
        ids(&read),
        [
            "github.com/gin-gonic/gin@1.9.1",
            "github.com/new/thing@1.2.0",
            "github.com/pkg/errors@0.9.1+incompatible",
            "golang.org/x/net@0.0.0-20220722155237-a158d28d115b"
        ]
    );
    assert_eq!(read.non_registry_entries, 1, "the local replace");
}

#[test]
fn go_mod_pre_117_completes_the_build_list_from_go_sum_highest() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("go.mod");
    let go_mod = "module example.com/old\n\ngo 1.16\n\nrequire github.com/a/a v1.2.0\n";
    std::fs::write(
        tmp.path().join("go.sum"),
        "github.com/a/a v1.1.0/go.mod h1:x=\n\
         github.com/a/a v1.2.0 h1:x=\n\
         github.com/b/b v0.3.0/go.mod h1:x=\n\
         github.com/b/b v0.10.0/go.mod h1:x=\n\
         github.com/b/b v0.10.0 h1:x=\n\
         golang.org/x/sys v0.0.0-20190412213103-97732733099d/go.mod h1:x=\n\
         golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f h1:x=\n",
    )
    .unwrap();
    let read = read(&path.display().to_string(), LockFormat::GoMod, go_mod);
    assert_eq!(
        ids(&read),
        [
            "github.com/a/a@1.2.0",
            "github.com/b/b@0.10.0",
            "golang.org/x/sys@0.0.0-20200930185726-fdedc70b468f"
        ]
    );
}

#[test]
fn read_dir_reports_unsupported_and_orphan_go_sum() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path();
    std::fs::write(dir.join("pom.xml"), "<project/>").unwrap();
    std::fs::write(dir.join("bun.lockb"), [0u8, 1, 2]).unwrap();
    std::fs::write(dir.join("go.sum"), "github.com/a/a v1.0.0 h1:x=\n").unwrap();
    std::fs::write(dir.join("package-lock.json"), "{ broken").unwrap();
    let outcomes = read_dir(dir);
    let unsupported = outcomes
        .iter()
        .filter(|o| matches!(o, LockfileOutcome::Unsupported { .. }))
        .count();
    let failed = outcomes
        .iter()
        .filter(|o| matches!(o, LockfileOutcome::Failed { .. }))
        .count();
    assert_eq!((unsupported, failed), (2, 2), "{outcomes:?}");
    assert!(probe(dir).is_some());

    let mut report = LockfileReport::default();
    for outcome in &outcomes {
        report.record(outcome);
    }
    let json = report.to_json();
    assert_eq!(json["failed_count"], 2);
    assert_eq!(json["unsupported_count"], 2);
}

#[test]
fn parse_lockfiles_under_flattens_every_directory() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    std::fs::create_dir_all(root.join("web")).unwrap();
    std::fs::create_dir_all(root.join("web").join("node_modules").join("x")).unwrap();
    std::fs::write(root.join("requirements.txt"), "flask==3.0.0\n").unwrap();
    std::fs::write(
        root.join("web").join("package-lock.json"),
        r#"{"lockfileVersion":3,"packages":{"node_modules/hono":{"version":"4.6.0"}}}"#,
    )
    .unwrap();
    std::fs::write(
        root.join("web")
            .join("node_modules")
            .join("x")
            .join("package-lock.json"),
        r#"{"lockfileVersion":3,"packages":{"node_modules/ignored":{"version":"1.0.0"}}}"#,
    )
    .unwrap();
    let (packages, problems) = parse_lockfiles_under(root);
    assert!(problems.is_empty(), "{problems:?}");
    let mut got: Vec<String> = packages
        .iter()
        .map(|p| format!("{}|{}|{}", p.ecosystem, p.name, p.version))
        .collect();
    got.sort();
    assert_eq!(got, ["PyPI|flask|3.0.0", "npm|hono|4.6.0"]);
}
