#!/usr/bin/env node
// Make sure THIS checkout's git hooks actually run.
//
// Husky's runtime shim (.husky/_) is generated by the `prepare` script of
// `pnpm install`. A fresh `git worktree add` never runs it, so in a new agent
// worktree `core.hooksPath` points at a directory that does not exist and every
// commit silently skips pre-commit / pre-push validation — no message, no error.
// Observed 2026-09-04: three PRs cut from worktrees reached CI with gates the
// hooks would have caught locally. Idempotent; safe to run anywhere in the repo.
//
//   pnpm run hooks:ensure
'use strict';
const { execSync, spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

function git(args) {
  return execSync(`git ${args}`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
}

let top;
try {
  top = git('rev-parse --show-toplevel');
} catch {
  console.error('ensure-hooks: not inside a git checkout');
  process.exit(2);
}

const shimDir = path.join(top, '.husky', '_');
const shimPresent = fs.existsSync(path.join(shimDir, 'h')) || fs.existsSync(path.join(shimDir, 'husky.sh'));
let hooksPath = '';
try {
  hooksPath = git('config --get core.hooksPath');
} catch {
  hooksPath = '';
}

if (shimPresent && hooksPath) {
  console.log(`ensure-hooks: OK — ${path.relative(top, shimDir)} present, core.hooksPath=${hooksPath}`);
  process.exit(0);
}

console.log(
  `ensure-hooks: ${shimPresent ? '' : '.husky/_ missing; '}${hooksPath ? '' : 'core.hooksPath unset; '}installing husky shim in ${top}`,
);
// `husky` (v9, no arguments) writes .husky/_ and sets core.hooksPath=.husky/_
// relative to the repo — the same thing `pnpm install` runs via `prepare`.
const res = spawnSync(process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm', ['exec', 'husky'], {
  cwd: top,
  stdio: 'inherit',
  shell: process.platform === 'win32',
});
if (res.status !== 0) {
  console.error('ensure-hooks: `pnpm exec husky` failed — run `pnpm install --frozen-lockfile` in this worktree');
  process.exit(res.status || 1);
}
const after = fs.existsSync(path.join(shimDir, 'h')) || fs.existsSync(path.join(shimDir, 'husky.sh'));
if (!after) {
  console.error('ensure-hooks: husky ran but .husky/_ is still missing');
  process.exit(1);
}
console.log(`ensure-hooks: installed — core.hooksPath=${git('config --get core.hooksPath')}`);
